### Create a Recipient
curl -X POST http://localhost:8080/recipients \
  -H "Content-Type: application/json" \
  -d '{
    "name": "andrew",
    "email": "andrew@boost.com"
}'

### Create a Special Offer
curl -X POST http://localhost:8080/offers \
  -H "Content-Type: application/json" \
  -d '{
    "name": "NEW2BOOST",
    "percentageDiscount": 15.0
}'

### Create a Voucher (update IDs as needed)
curl -X POST http://localhost:8080/vouchers/create \
  -H "Content-Type: application/json" \
  -d '{
    "recipientEmail": "andrew@boost.com",
    "offerName": "NEW2BOOST",
    "expirationDate": "2025-12-31"
}'

### Check for valid Vouchers
curl -X GET "http://172.21.240.1:8080/vouchers/valid?email=andrew@boost.com"

### Redeem a Voucher
curl -X POST http://localhost:8080/vouchers/redeem/{VOUCHER_CODE}

